### ISSUE TITLE
article review

### ISSUE THREAD

**Issue by mattatnersc** [kellyrowland/hpcsyspros19#6]
I looked over the article and have the following feedback:

- I made a few edits in this PR: https://github.com/kellyrowland/hpcsyspros19/pull/5
- I find the following sentences to be awkward.
  - `NERSC is not the first organization to implement multi-factor authentication (MFA) for its users, and we had seen multiple talks by other supercomputing facilities who had deployed MFA.`  The switch from present tense to the pluperfect feels awkward to me.
  - `In addition, NERSC wanted to make it possible for users whose tokens were not immediately available to not be stuck and unable to work.`  The phrase `not be stuck` also feels awkward to me.  I'm not sure how to re-word it, but I would try to remove the negatives, `In addition, NERSC wanted to make it possible for users whose tokens were not immediately available to be able to work` or something along those lines.
- Lastly, in Figure 2, the sshproxy architecture has a "revocation lists", which is a feature that doesn't exist.

**Comment by kellyrowland** [comment]
@scanon are you able to put up a corrected version of the sshproxy architecture diagram?

**Comment by kellyrowland** [comment]
Fixed wording and updated sshproxy architecture diagram.
